list(
  APPEND
  LV_EDITOR_PROJECT_SOURCES
  ${CMAKE_CURRENT_LIST_DIR}/components/basic/bar/bar_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/basic/button/button_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/basic/card/card_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/basic/card/card_header_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/basic/circle_button/circle_button_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/basic/column/column_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/basic/div/div_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/basic/icon_button/icon_button_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/basic/roller/roller_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/basic/row/row_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/basic/slider/slider_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/basic/switch/switch_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/basic/table/table_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/cards/alarm/alarm_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/cards/light_temperature/light_temperature_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/cards/move_goal/move_goal_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/cards/move_goal/stat_col_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/cards/music_player/music_player_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/cards/speaker_volume/speaker_volume_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/cards/theme_swtcher/theme_switcher_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/cards/thermostat/thermostat_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/cards/weather/location_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/cards/weather/weather_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/examples_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/examples.c
  ${CMAKE_CURRENT_LIST_DIR}/screens/elements_gen.c)