list(
  APPEND
  LV_EDITOR_PROJECT_SOURCES
  ${CMAKE_CURRENT_LIST_DIR}/fonts/montserrat_14_c_array_data.c
  ${CMAKE_CURRENT_LIST_DIR}/fonts/montserrat_16_bin_file_data.c
  ${CMAKE_CURRENT_LIST_DIR}/fonts/Montserrat_Medium_ttf_data.c
  ${CMAKE_CURRENT_LIST_DIR}/images/flower_data_data.c
  ${CMAKE_CURRENT_LIST_DIR}/screens/screen_assets_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/ui_assets_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/ui_assets.c)