list(
  APPEND
  LV_EDITOR_PROJECT_SOURCES
  ${CMAKE_CURRENT_LIST_DIR}/components/button/button_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/column/column_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/row/row_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/screens/screen_layouts_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/ui_layouts_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/ui_layouts.c)